products = {'wheat':'WHEAT',
            'enchanted bread':'ENCHANTED_BREAD',
            'e bread':'ENCHANTED_BREAD',
            'hay bale':'HAY_BLOCK',
            'enchanted hay bale':'ENCHANTED_HAY_BLOCK',
            'e hay bale':'ENCHANTED_HAY_BLOCK',
            'carrot':'CARROT_ITEM',
            'enchanted carrot':'ENCHANTED_CARROT',
            'e carrot':'ENCHANTED_CARROT',
            'enchanted carrot on a stick':'ENCHANTED_CARROT_ON_A_STICK',
            'e carrot on a stick':'ENCHANTED_CARROT_ON_A_STICK',
            'enchanted golden carrot':'ENCHANTED_GOLDEN_CARROT',
            'e golden carrot':'ENCHANTED_GOLDEN_CARROT',
            'potato':'POTATO_ITEM',
            'enchanted potato':'ENCHANTED_POTATO',
            'e potato':'ENCHANTED_POTATO',
            'enchanted baked potato':'ENCHANTED_BAKED_POTATO',
            'e baked potato':'ENCHANTED_BAKED_POTATO',
            'pumpkin':'PUMPKIN',
            'enchanted pumpkin':'ENCHANTED_PUMPKIN',
            'e pumpkin':'ENCHANTED_PUMPKIN',
            'melon slice':'MELON',
            'melon':'MELON',
            'enchanted melon':'ENCHANTED_MELON',
            'e melon':'ENCHANTED_MELON',
            'enchanted glistering melon':'ENCHANTED_GLISTERING_MELON',
            'e glistering melon':'ENCHANTED_GLISTERING_MELON',
            'enchanted melon block':'ENCHANTED_MELON_BLOCK',
            'e melon block':'ENCHANTED_MELON_BLOCK',
            'wheat seeds':'SEEDS',
            'seeds':'SEEDS',
            'enchanted seeds':'ENCHANTED_SEEDS',
            'e seeds':'ENCHANTED_SEEDS',
            'red mushroom':'RED_MUSHROOM',
            'enchanted red mushroom':'ENCHANTED_RED_MUSHROOM',
            'e red mushroom':'ENCHANTED_RED_MUSHROOM',
            'red mushroom block':'HUGE_MUSHROOM_2',
            'enchanted red mushroom block':'ENCHANTED_HUGE_MUSHROOM_2',
            'e red mushroom block':'ENCHANTED_HUGE_MUSHROOM_2',
            'brown mushroom':'BROWN_MUSHROOM',
            'enchanted brown mushroom':'ENCHANTED_BROWN_MUSHROOM',
            'e brown mushroom':'ENCHANTED_BROWN_MUSHROOM',
            'brown mushroom block': 'HUGE_MUSHROOM_1',
            'enchanted brown mushroom block': 'ENCHANTED_HUGE_MUSHROOM_1',
            'e brown mushroom block':'ENCHANTED_HUGE_MUSHROOM_1',
            'cocoa beans':'INK_SACK:3',
            'enchanted cocoa beans':'ENCHANTED_COCOA',
            'e cocoa beans':'ENCHANTED_COCOA',
            'enchanted cookie':'ENCHANTED_COOKIE',
            'e cookie':'ENCHANTED_COOKIE',
            'cactus':'CACTUS',
            'enchanted cactus green':'ENCHANTED_CACTUS_GREEN',
            'e cactus green':'ENCHANTED_CACTUS_GREEN',
            'enchanted cactus':'ENCHANTED_CACTUS',
            'e cactus':'ENCHANTED_CACTUS',
            'sugar cane':'SUGAR_CANE',
            'enchanted sugar':'ENCHANTED_SUGAR',
            'e sugar':'ENCHANTED_SUGAR',
            'enchanted paper':'ENCHANTED_PAPER',
            'e paper':'ENCHANTED_PAPER',
            'enchanted sugar cane':'ENCHANTED_SUGAR_CANE',
            'e sugar cane':'ENCHANTED_SUGAR_CANE',
            'feather':'FEATHER',
            'enchanted feather':'ENCHANTED_FEATHER',
            'e feather':'ENCHANTED_FEATHER',
            'leather':'LEATHER',
            'enchanted leather':'ENCHANTED_LEATHER',
            'e leather':'ENCHANTED_LEATHER',
            'raw beef':'RAW_BEEF',
            'enchanted raw beef':'ENCHANTED_RAW_BEEF',
            'enchanted beef':'ENCHANTED_RAW_BEEF',
            'e beef':'ENCHANTED_RAW_BEEF',
            'raw porkchop':'PORK',
            'pork':'PORK',
            'enchanted pork':'ENCHANTED_PORK',
            'e pork':'ENCHANTED_PORK',
            'enchanted grilled pork':'ENCHANTED_GRILLED_PORK',
            'e grilled pork':'ENCHANTED_GRILLED_PORK',
            'raw chicken':'RAW_CHICKEN',
            'chicken':'RAW_CHICKEN',
            'enchanted raw chicken':'ENCHANTED_RAW_CHICKEN',
            'e chicken':'ENCHANTED_RAW_CHICKEN',
            'e raw chicken':'ENCHANTED_RAW_CHICKEN',
            'enchanted egg':'ENCHANTED_EGG',
            'e egg':'ENCHANTED_EGG',
            'enchanted cake':'ENCHANTED_CAKE',
            'e cake':'ENCHANTED_CAKE',
            'super enchanted egg':'SUPER_EGG',
            'raw mutton':'MUTTON',
            'mutton':'MUTTON',
            'enchanted mutton':'ENCHANTED_MUTTON',
            'e mutton':'ENCHANTED_MUTTON',
            'enchanted cooked mutton':'ENCHANTED_COOKED_MUTTON',
            'e cooked mutton':'ENCHANTED_COOKED_MUTTON',
            'raw rabbit':'RABBIT',
            'rabbit':'RABBIT',
            'enchanted raw rabbit':'ENCHANTED_RABBIT',
            'e rabbit':'ENCHANTED_RABBIT',
            'rabbit foot':'RABBIT_FOOT',
            'enchanted rabbit foot':'ENCHANTED_RABBIT_FOOT',
            'e rabbit foot':'ENCHANTED_RABBIT_FOOT',
            'rabbit hide':'RABBIT_HIDE',
            'enchanted rabbit hide':'ENCHANTED_RABBIT_HIDE',
            'e rabbit hide':'ENCHANTED_RABBIT_HIDE',
            'nether wart':'NETHER_STALK',
            'enchanted nether wart':'ENCHANTED_NETHER_STALK',
            'e nether wart':'ENCHANTED_NETHER_STALK',
            'cobblestone':'COBBLESTONE',
            'cobble':'COBBLESTONE',
            'enchanted cobblestone':'ENCHANTED_COBBLESTONE',
            'e cobblestone':'ENCHANTED_COBBLESTONE',
            'e cobble':'ENCHANTED_COBBLESTONE',
            'coal':'COAL',
            'enchanted coal':'ENCHANTED_COAL',
            'e coal':'ENCHANTED_COAL',
            'enchanted charcoal':'ENCHANTED_CHARCOAL',
            'e charcoal':'ENCHANTED_CHARCOAL',
            'enchanted block of coal':'ENCHANTED_COAL_BLOCK',
            'e coal block':'ENCHANTED_COAL_BLOCK',
            'e block of coal':'ENCHANTED_COAL_BLOCK',
            'iron ingot':'IRON_INGOT',
            'iron':'IRON_INGOT',
            'enchanted iron ingot':'ENCHANTED_IRON',
            'enchanted iron':'ENCHANTED_IRON',
            'e iron':'ENCHANTED_IRON',
            'enchanted iron block':'ENCHANTED_IRON_BLOCK',
            'e iron block':'ENCHANTED_IRON_BLOCK',
            'gold ingot':'GOLD_INGOT',
            'gold':'GOLD_INGOT',
            'enchanted gold ingot':'ENCHANTED_GOLD',
            'enchanted gold':'ENCHANTED_GOLD',
            'e gold':'ENCHANTED_GOLD',
            'enchanted gold block':'ENCHANTED_GOLD_BLOCK',
            'e gold block':'ENCHANTED_GOLD_BLOCK',
            'diamond':'DIAMOND',
            'enchanted diamond':'ENCHANTED_DIAMOND',
            'e diamond':'ENCHANTED_DIAMOND',
            'enchanted diamond block':'ENCHANTED_DIAMOND_BLOCK',
            'e diamond block':'ENCHANTED_DIAMOND_BLOCK',
            'lapis lazuli':'INK_SACK:4',
            'lapis':'INK_SACK:4',
            'enchanted lapis lazuli':'ENCHANTED_LAPIS_LAZULI',
            'e lapis':'ENCHANTED_LAPIS_LAZULI',
            'enchanted lapis':'ENCHANTED_LAPIS_LAZULI',
            'enchanted lapis block':'ENCHANTED_LAPIS_LAZULI_BLOCK',
            'e lapis block':'ENCHANTED_LAPIS_LAZULI_BLOCK',
            'emerald':'EMERALD',
            'enchanted emerald':'ENCHANTED_EMERALD',
            'e emerald':'ENCHANTED_EMERALD',
            'enchanted emerald block':'ENCHANTED_EMERALD_BLOCK',
            'e emerald block':'ENCHANTED_EMERALD_BLOCK',
            'redstone':'REDSTONE',
            'enchanted redstone':'ENCHANTED_REDSTONE',
            'e redstone':'ENCHANTED_REDSTONE',
            'enchanted redstone block':'ENCHANTED_REDSTONE_BLOCK',
            'e redstone block':'ENCHANTED_REDSTONE_BLOCK',
            'quartz':'QUARTZ',
            'enchanted quartz':'ENCHANTED_QUARTZ',
            'e quartz':'ENCHANTED_QUARTZ',
            'enchanted quartz block':'ENCHANTED_QUARTZ_BLOCK',
            'e quartz block':'ENCHANTED_QUARTZ_BLOCK',
            'obsidian':'OBSIDIAN',
            'enchanted obsidian':'ENCHANTED_OBSIDIAN',
            'e obsidian':'ENCHANTED_OBSIDIAN',
            'glowstone dust':'GLOWSTONE_DUST',
            'enchanted glowstone dust':'ENCHANTED_GLOWSTONE_DUST',
            'e glowstone dust':'ENCHANTED_GLOWSTONE_DUST',
            'enchanted glowstone':'ENCHANTED_GLOWSTONE',
            'e glowstone':'ENCHANTED_GLOWSTONE',
            'gravel':'GRAVEL',
            'flint':'FLINT',
            'enchanted flint':'ENCHANTED_FLINT',
            'e flint':'ENCHANTED_FLINT',
            'ice':'ICE',
            'packed ice':'PACKED_ICE',
            'enchanted ice':'ENCHANTED_ICE',
            'e ice':'ENCHANTED_ICE',
            'enchanted packed ice':'ENCHANTED_PACKED_ICE',
            'e packed ice':'ENCHANTED_PACKED_ICE',
            'netherrack':'NETHERRACK',
            'sand':'SAND',
            'enchanted sand':'ENCHANTED_SAND',
            'e sand':'ENCHANTED_SAND',
            'end stone':'ENDER_STONE',
            'enchanted end stone':'ENCHANTED_ENDSTONE',
            'e end stone':'ENCHANTED_ENDSTONE',
            'snowball':'SNOW_BALL',
            'snow block':'SNOW_BLOCK',
            'enchanted snow block':'ENCHANTED_SNOW_BLOCK',
            'e snow block':'ENCHANTED_SNOW_BLOCK',
            'rotten flesh':'ROTTEN_FLESH',
            'enchanted rotten flesh':'ENCHANTED_ROTTEN_FLESH',
            'e rotten flesh':'ENCHANTED_ROTTEN_FLESH',
            'bone':'BONE',
            'enchanted bone':'ENCHANTED_BONE',
            'e bone':'ENCHANTED_BONE',
            'string':'STRING',
            'enchanted string':'ENCHANTED_STRING',
            'e string':'ENCHANtED_STRING',
            'spider eye':'SPIDER_EYE',
            'enchanted spider eye':'ENCHANTED_SPIDER_EYE',
            'e spider eye':'ENCHANTED_SPIDER_EYE',
            'enchanted fermented spider eye':'ENCHANTED_FERMENTED_SPIDER_EYE',
            'e fermented spider eye':'ENCHANTED_FERMENTED_SPIDER_EYE',
            'gunpowder':'SULPHUR',
            'enchanted gunpowder':'ENCHANTED_GUNPOWDER',
            'e gunpowder':'ENCHANTED_GUNPOWDER',
            'enchanted firework rocket':'ENCHANTED_FIREWORK_ROCKET',
            'e firework rocket':'ENCHANTED_FIREWORK_ROCKET',
            'ender pearl':'ENDER_PEARL',
            'e pearl':'ENDER_PEARL',
            'enchanted ender pearl':'ENCHANTED_ENDER_PEARL',
            'e ender pearl':'ENCHANTED_ENDER_PEARL',
            'enchanted eye of ender':'ENCHANTED_EYE_OF_ENDER',
            'e eye of ender':'ENCHANTED_EYE_OF_ENDER',
            'ghast tear':'GHAST_TEAR',
            'enchanted ghast tear':'ENCHANTED_GHAST_TEAR',
            'e ghast tear':'ENCHANTED_GHAST_TEAR',
            'slimeball':'SLIME_BALL',
            'enchanted slimeball':'ENCHANTED_SLIME_BALL',
            'e slimeball':'ENCHANTED_SLIME_BALL',
            'enchanted slime block':'ENCHANTED_SLIME_BLOCK',
            'e slime block':'ENCHANTED_SLIME_BLOCK',
            'blaze rod':'BLAZE_ROD',
            'enchanted blaze powder':'ENCHANTED_BLAZE_POWDER',
            'e blaze powder':'ENCHANTED_BLAZE_POWDER',
            'enchanted blaze rod':'ENCHANTED_BLAZE_ROD',
            'e blaze rod':'ENCHANTED_BLAZE_ROD',
            'magma cream':'MAGMA_CREAM',
            'enchanted magma cream':'ENCHANTED_MAGMA_CREAM',
            'e magma cream':'ENCHANTED_MAGMA_CREAM',
            'oak wood':'LOG',
            'enchanted oak wood':'ENCHANTED_OAK_LOG',
            'e oak log':'ENCHANTED_OAK_LOG',
            'spruce wood':'LOG:1',
            'enchanted spruce wood':'ENCHANTED_SPURCE_LOG',
            'e spruce wood':'ENCHANTED_SPRUCE_LOG',
            'birch wood':'LOG:2',
            'enchanted birch wood':'ENCHANTED_BIRCH_LOG',
            'e birch wood':'ENCHANTED_BIRCH_LOG',
            'dark oak wood':'LOG_2:1',
            'enchanted dark oak wood':'ENCHANTED_DARK_OAK_LOG',
            'e dark oak wood':'ENCHANTED_DARK_OAK_LOG',
            'acacia wood':'LOG_2',
            'enchanted acacia wood':'ENCHANTED_ACACIA_LOG',
            'e acacia wood':'ENCHANTED_ACACIA_LOG',
            'jungle wood':'LOG:3',
            'enchanted jungle wood':'ENCHANTED_JUNGLE_LOG',
            'e jungle wood':'ENCHANTED_JUNGLE_LOG',
            'raw fish':'RAW_FISH',
            'enchanted raw fish':'ENCHANTED_RAW_FISH',
            'e raw fish':'ENCHANTED_RAW_FISH',
            'enchanted cooked fish':'ENCHANTED_COOKED_FISH',
            'e cooked fish':'ENCHANTED_COOKED_FISH',
            'raw salmon':'RAW_FISH:1',
            'enchanted raw salmon':'ENCHANTED_RAW_SALMON',
            'e raw salmon':'ENCHANTED_RAW_SALMON',
            'enchanted cooked salmon':'ENCHANTED_COOKED_SALMON',
            'e cooked salmon':'ENCHANTED_COOKED_SALMON',
            'clownfish':'RAW_FISH:2',
            'enchanted clownfish':'ENCHANTED_CLOWNFISH',
            'e clownfish':'ENCHANTED_CLOWNFISH',
            'pufferfish':'RAW_FISH:3',
            'enchanted pufferfish':'ENCHANTED_PUFFERFISH',
            'e pufferfish':'ENCHANTED_PUFFERFISH',
            'prismarine shard':'PRISMARINE_SHARD',
            'enchanted prismarine shard':'ENCHANTED_PRISMARINE_SHARD',
            'e prismarine shard':'ENCHANTED_PRISMARINE_SHARD',
            'prismarine crystals':'PRIMARINE_CRYSTALS',
            'enchanted prismarine crystals':'ENCHANTED_PRISMARINE_CRYSTALS',
            'e prismarine crystals':'ENCHANTED_PRISMARINE_CRSTALS',
            'clay':'CLAY_BALL',
            'enchanted clay':'ENCHANTED_CLAY_BALL',
            'e clay':'ENCHANTED_CLAY_BALL',
            'lily pad':'WATER_LILY',
            'enchanted lily pad':'ENCHANTED_WATER_LILY',
            'e lily pad':'ENCHANTED_WATER_LILY',
            'ink sack':'INK_SACK',
            'enchanted ink sack':'ENCHANTED_INK_SACK',
            'e ink sack':'ENCHANTED_INK_SACK',
            'sponge':'SPONGE',
            'enchanted sponge':'ENCHANTED_SPONGE',
            'e sponge':'ENCHANTED_SPONGE',
            'enchanted wet sponge':'ENCHANTED_WET_SPONGE',
            'e wet sponge':'ENCHANTED_WET_SPONGE',
            'revenant flesh':'REVENANT_FLESH',
            'revenant viscera':'REVENANT_VISCERA',
            'tarantula web':'TARANTULA_WEB',
            'tarantula silk':'TARANTULA_SILK',
            'wolf tooth':'WOLF_TOOTH',
            'golden tooth':'GOLDEN_TOOTH',
            'hot potato book':'HOT_POTATO_BOOK',
            'compactor':'COMPACTOR',
            'super compactor 3000':'SUPER_COMPACTOR_3000',
            'sc3000':'SUPER_COMPACTOR_3000',
            'summoning  eye':'SUMMONING_EYE',
            'protector dragon fragment':'PROTECTOR_FRAGMENT',
            'protector frag':'PROTECTOR_FRAGMENT',
            'old dragon fragment':'OLD_FRAGMENT',
            'old frag':'OLD_FRAGMENT',
            'unstable dragon fragment':'UNSTABLE_FRAGMENT',
            'unstable frag':'UNSTABLE_FRAGMENT',
            'strong dragon fragment':'STRONG_FRAGMENT',
            'strong frag':'STRONG_FRAGMENT',
            'young dragon fragment':'YOUNG_FRAGMENT',
            'young frag':'YOUNG_FRAGMENT',
            'wise dragon fragment':'WISE_FRAGMENT',
            'wise frag':'WISE_FRAGMENT',
            'superior dragon fragment':'SUPERIOR_FRAGMENT',
            'superior frag':'SUPERIOR_FRAGMENT',
            'enchanted redstone lmap':'ENCHANTED_REDSTONE_LAMP',
            'enchanted lava bucket':'ENCHANTED_LAVA_BUCKET',
            'e lava bucket':'ENCHANTED_LAVA_BUCKET',
            'hamster wheel':'HAMSTER_WHEEL',
            'foul flesh':'FOUL_FLESH',
            'catalyst':'CATALYST',
            'green candy':'GREEN_CANDY',
            'purple candy':'PURPLE_CANDY',
            'white gift':'WHITE_GIFT',
            'green gift':'GREEN_GIFT',
            'red gift':'RED_GIFT',
            'stock of stonks':'STOCK_OF_STONKS',
            'stonks':'STOCK_OF_STONKS'
}