items = {'wheat':'WHEAT',
        'enchanted bread':'ENCHANTED_BREAD',
        'hay bale':'HAY_BLOCK',
        'enchanted hay bale':'ENCHANTED_HAY_BLOCK',
        'carrot':'CARROT_ITEM',
        'enchanted carrot':'ENCHANTED_CARROT',
        'enchanted carrot on a stick':'ENCHANTED_CARROT_STICK',
        'enchanted golden carrot':'ENCHANTED_GOLDEN_CARROT',
        'potato':'POTATO_ITEM',
        'enchanted potato':'ENCHANTED_POTATO',
        'enchanted baked potato':'ENCHANTED_BAKED_POTATO',
        'pumpkin':'PUMPKIN',
        'enchanted pumpkin':'ENCHANTED_PUMPKIN',
        'melon':'MELON',
        'enchanted melon':'ENCHANTED_MELON',
        'enchanted glistering melon':'ENCHANTED_GLISTERING_MELON',
        'enchanted melon block':'ENCHANTED_MELON_BLOCK',
        'seeds':'SEEDS',
        'enchanted seeds':'ENCHANTED_SEEDS',
        'red mushroom':'RED_MUSHROOM',
        'enchanted red mushroom':'ENCHANTED_RED_MUSHROOM',
        'red mushroom block':'HUGE_MUSHROOM_2',
        'enchanted red mushroom block':'ENCHANTED_HUGE_MUSHROOM_2',
        'brown mushroom':'BROWN_MUSHROOM',
        'enchanted brown mushroom':'ENCHANTED_BROWN_MUSHROOM',
        'brown mushroom block': 'HUGE_MUSHROOM_1',
        'enchanted brown mushroom block': 'ENCHANTED_HUGE_MUSHROOM_1',
        'cocoa beans':'INK_SACK:3',
        'enchanted cocoa beans':'ENCHANTED_COCOA',
        'enchanted cookie':'ENCHANTED_COOKIE',
        'cactus':'CACTUS',
        'enchanted cactus green':'ENCHANTED_CACTUS_GREEN',
        'enchanted cactus':'ENCHANTED_CACTUS',
        'sugar cane':'SUGAR_CANE',
        'enchanted sugar':'ENCHANTED_SUGAR',
        'enchanted paper':'ENCHANTED_PAPER',
        'enchanted sugar cane':'ENCHANTED_SUGAR_CANE',
        'feather':'FEATHER',
        'enchanted feather':'ENCHANTED_FEATHER',
        'leather':'LEATHER',
        'enchanted leather':'ENCHANTED_LEATHER',
        'raw beef':'RAW_BEEF',
        'enchanted raw beef':'ENCHANTED_RAW_BEEF',
        'raw porkchop':'PORK',
        'enchanted pork':'ENCHANTED_PORK',
        'enchanted grilled pork':'ENCHANTED_GRILLED_PORK',
        'raw chicken':'RAW_CHICKEN',
        'enchanted raw chicken':'ENCHANTED_RAW_CHICKEN',
        'enchanted egg':'ENCHANTED_EGG',
        'enchanted cake':'ENCHANTED_CAKE',
        'super enchanted egg':'SUPER_EGG',
        'raw mutton':'MUTTON',
        'enchanted mutton':'ENCHANTED_MUTTON',
        'enchanted cooked mutton':'ENCHANTED_COOKED_MUTTON',
        'raw rabbit':'RABBIT',
        'enchanted raw rabbit':'ENCHANTED_RABBIT',
        'rabbit foot':'RABBIT_FOOT',
        'enchanted rabbit foot':'ENCHANTED_RABBIT_FOOT',
        'rabbit hide':'RABBIT_HIDE',
        'enchanted rabbit hide':'ENCHANTED_RABBIT_HIDE',
        'nether wart':'NETHER_STALK',
        'enchanted nether wart':'ENCHANTED_NETHER_STALK',
        'cobblestone':'COBBLESTONE',
        'enchanted cobblestone':'ENCHANTED_COBBLESTONE',
        'coal':'COAL',
        'enchanted coal':'ENCHANTED_COAL',
        'enchanted charcoal':'ENCHANTED_CHARCOAL',
        'enchanted block of coal':'ENCHANTED_COAL_BLOCK',
        'iron ingot':'IRON_INGOT',
        'enchanted iron ingot':'ENCHANTED_IRON',
        'enchanted iron block':'ENCHANTED_IRON_BLOCK',
        'gold ingot':'GOLD_INGOT',
        'enchanted gold ingot':'ENCHANTED_GOLD',
        'enchanted gold block':'ENCHANTED_GOLD_BLOCK',
        'diamond':'DIAMOND',
        'enchanted diamond':'ENCHANTED_DIAMOND',
        'enchanted diamond block':'ENCHANTED_DIAMOND_BLOCK',
        'lapis lazuli':'INK_SACK:4',
        'enchanted lapis lazuli':'ENCHANTED_LAPIS_LAZULI',
        'enchanted lapis block':'ENCHANTED_LAPIS_LAZULI_BLOCK',
        'emerald':'EMERALD',
        'enchanted emerald':'ENCHANTED_EMERALD',
        'enchanted emerald block':'ENCHANTED_EMERALD_BLOCK',
        'redstone':'REDSTONE',
        'enchanted redstone':'ENCHANTED_REDSTONE',
        'enchanted redstone block':'ENCHANTED_REDSTONE_BLOCK',
        'quartz':'QUARTZ',
        'enchanted quartz':'ENCHANTED_QUARTZ',
        'enchanted quartz block':'ENCHANTED_QUARTZ_BLOCK',
        'obsidian':'OBSIDIAN',
        'enchanted obsidian':'ENCHANTED_OBSIDIAN',
        'glowstone dust':'GLOWSTONE_DUST',
        'enchanted glowstone dust':'ENCHANTED_GLOWSTONE_DUST',
        'enchanted glowstone':'ENCHANTED_GLOWSTONE',
        'gravel':'GRAVEL',
        'flint':'FLINT',
        'enchanted flint':'ENCHANTED_FLINT',
        'ice':'ICE',
        'packed ice':'PACKED_ICE',
        'enchanted ice':'ENCHANTED_ICE',
        'enchanted packed ice':'ENCHANTED_PACKED_ICE',
        'netherrack':'NETHERRACK',
        'sand':'SAND',
        'enchanted sand':'ENCHANTED_SAND',
        'end stone':'ENDER_STONE',
        'enchanted end stone':'ENCHANTED_ENDSTONE',
        'snowball':'SNOW_BALL',
        'snow block':'SNOW_BLOCK',
        'enchanted snow block':'ENCHANTED_SNOW_BLOCK',
        'rotten flesh':'ROTTEN_FLESH',
        'enchanted rotten flesh':'ENCHANTED_ROTTEN_FLESH',
        'bone':'BONE',
        'enchanted bone':'ENCHANTED_BONE',
        'string':'STRING',
        'enchanted string':'ENCHANTED_STRING',
        'spider eye':'SPIDER_EYE',
        'enchanted spider eye':'ENCHANTED_SPIDER_EYE',
        'enchanted fermented spider eye':'ENCHANTED_FERMENTED_SPIDER_EYE',
        'gunpowder':'SULPHUR',
        'enchanted gunpowder':'ENCHANTED_GUNPOWDER',
        'enchanted firework rocket':'ENCHANTED_FIREWORK_ROCKET',
        'ender pearl':'ENDER_PEARL',
        'enchanted ender pearl':'ENCHANTED_ENDER_PEARL',
        'enchanted eye of ender':'ENCHANTED_EYE_OF_ENDER',
        'ghast tear':'GHAST_TEAR',
        'enchanted ghast tear':'ENCHANTED_GHAST_TEAR',
        'slimeball':'SLIME_BALL',
        'enchanted slimeball':'ENCHANTED_SLIME_BALL',
        'enchanted slime block':'ENCHANTED_SLIME_BLOCK',
        'blaze rod':'BLAZE_ROD',
        'enchanted blaze powder':'ENCHANTED_BLAZE_POWDER',
        'enchanted blaze rod':'ENCHANTED_BLAZE_ROD',
        'magma cream':'MAGMA_CREAM',
        'enchanted magma cream':'ENCHANTED_MAGMA_CREAM',
        'oak wood':'LOG',
        'enchanted oak wood':'ENCHANTED_OAK_LOG',
        'spruce wood':'LOG:1',
        'enchanted spruce wood':'ENCHANTED_SPRUCE_LOG',
        'birch wood':'LOG:2',
        'enchanted birch wood':'ENCHANTED_BIRCH_LOG',
        'dark oak wood':'LOG_2:1',
        'enchanted dark oak wood':'ENCHANTED_DARK_OAK_LOG',
        'acacia wood':'LOG_2',
        'enchanted acacia wood':'ENCHANTED_ACACIA_LOG',
        'jungle wood':'LOG:3',
        'enchanted jungle wood':'ENCHANTED_JUNGLE_LOG',
        'raw fish':'RAW_FISH',
        'enchanted raw fish':'ENCHANTED_RAW_FISH',
        'enchanted cooked fish':'ENCHANTED_COOKED_FISH',
        'raw salmon':'RAW_FISH:1',
        'enchanted raw salmon':'ENCHANTED_RAW_SALMON',
        'enchanted cooked salmon':'ENCHANTED_COOKED_SALMON',
        'clownfish':'RAW_FISH:2',
        'enchanted clownfish':'ENCHANTED_CLOWNFISH',
        'pufferfish':'RAW_FISH:3',
        'enchanted pufferfish':'ENCHANTED_PUFFERFISH',
        'prismarine shard':'PRISMARINE_SHARD',
        'enchanted prismarine shard':'ENCHANTED_PRISMARINE_SHARD',
        'prismarine crystals':'PRISMARINE_CRYSTALS',
        'enchanted prismarine crystals':'ENCHANTED_PRISMARINE_CRYSTALS',
        'clay':'CLAY_BALL',
        'enchanted clay':'ENCHANTED_CLAY_BALL',
        'lily pad':'WATER_LILY',
        'enchanted lily pad':'ENCHANTED_WATER_LILY',
        'ink sack':'INK_SACK',
        'enchanted ink sack':'ENCHANTED_INK_SACK',
        'sponge':'SPONGE',
        'enchanted sponge':'ENCHANTED_SPONGE',
        'enchanted wet sponge':'ENCHANTED_WET_SPONGE',
        'revenant flesh':'REVENANT_FLESH',
        'revenant viscera':'REVENANT_VISCERA',
        'tarantula web':'TARANTULA_WEB',
        'tarantula silk':'TARANTULA_SILK',
        'wolf tooth':'WOLF_TOOTH',
        'golden tooth':'GOLDEN_TOOTH',
        'hot potato book':'HOT_POTATO_BOOK',
        'compactor':'COMPACTOR',
        'super compactor 3000':'SUPER_COMPACTOR_3000',
        'summoning  eye':'SUMMONING_EYE',
        'protector dragon fragment':'PROTECTOR_FRAGMENT',
        'old dragon fragment':'OLD_FRAGMENT',
        'unstable dragon fragment':'UNSTABLE_FRAGMENT',
        'strong dragon fragment':'STRONG_FRAGMENT',
        'young dragon fragment':'YOUNG_FRAGMENT',
        'wise dragon fragment':'WISE_FRAGMENT',
        'superior dragon fragment':'SUPERIOR_FRAGMENT',
        'enchanted redstone lmap':'ENCHANTED_REDSTONE_LAMP',
        'enchanted lava bucket':'ENCHANTED_LAVA_BUCKET',
        'hamster wheel':'HAMSTER_WHEEL',
        'foul flesh':'FOUL_FLESH',
        'catalyst':'CATALYST',
        'green candy':'GREEN_CANDY',
        'purple candy':'PURPLE_CANDY',
        'white gift':'WHITE_GIFT',
        'green gift':'GREEN_GIFT',
        'red gift':'RED_GIFT',
        'stock of stonks':'STOCK_OF_STONKS',
        'carrot bait':'CARROT_BAIT',
        'minnow bait':'MINNOW_BAIT',
        'fish bait':'FISH_BAIT',
        'light bait':'LIGHT_BAIT',
        'dark bait':'DARK_BAIT',
        'spooky bait':'SPOOKY_BAIT',
        'spiked bait':'SPIKED_BAIT',
        'blessed bait':'BLESSED_BAIT',
        'ice bait':'ICE_BAIT',
        'whale bait':'WHALE_BAIT'
}